#define NATIVE_DIRECT_INDEXED_INDIRECT_D_X_READ

#define NATIVE_STACK_RELATIVE_READ

#define NATIVE_DIRECT_READ

#define NATIVE_DIRECT_INDIRECT_LONG_READ

#define NATIVE_IMMEDIATE_READ

#define NATIVE_ABSOLUTE_READ

#define NATIVE_ABSOLUTE_LONG_READ

#define NATIVE_INDIRECT_INDEXED_D_Y_READ

#define NATIVE_DIRECT_INDIRECT_READ

#define NATIVE_STACK_RELATIVE_INDIRECT_INDEXED_READ

#define NATIVE_DIRECT_X_READ

#define NATIVE_DIRECT_INDIRECT_INDEXED_LONG_D_Y_READ

#define NATIVE_ABSOLUTE_Y_READ

#define NATIVE_ABSOLUTE_X_READ

#define NATIVE_ABSOLUTE_LONG_X_READ
